# Generated by Django 5.1.2 on 2024-10-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_barbershop_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barbershop',
            old_name='foto',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='barbershop',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
