# Generated by Django 5.0.4 on 2024-10-10 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('barbershop', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Barber_Barbershop', to='core.barbershop')),
                ('service', models.ManyToManyField(related_name='Service_Barber', to='core.service')),
            ],
        ),
    ]
