# Generated by Django 5.1.2 on 2024-10-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_barbeiro_contrato_remove_usuario_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fotos',
            field=models.ImageField(null=True, upload_to='fotos/'),
        ),
    ]
