# Generated by Django 5.0.4 on 2024-10-10 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbershop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('hours', models.TimeField()),
                ('confirm', models.BooleanField()),
                ('Responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Schedule_Service', to='barbershop.barber')),
            ],
            options={
                'unique_together': {('date', 'hours', 'Responsible')},
            },
        ),
    ]
