# Generated by Django 5.0.4 on 2024-10-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schendules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
