# Generated by Django 5.0.4 on 2024-10-10 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schendules', '0002_alter_schedule_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='confirm',
        ),
    ]
