# Generated by Django 5.0.4 on 2024-10-11 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('schendules', '0003_remove_schedule_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='barbershop',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='schendule_barbershop', to='core.barbershop'),
            preserve_default=False,
        ),
    ]
