# Generated by Django 5.0.4 on 2024-10-11 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('schendules', '0004_schedule_barbershop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='barbershop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schendule_barbershop', to='core.barbershop'),
        ),
    ]
